# -*- coding: utf-8 -*-
"""422 Project group_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7tW6H04fYNhasuTNw2fOXSYcl4iJE4t

Importing Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import tensorflow as tf

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.cluster import KMeans

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve,
    auc,
    confusion_matrix,
    matthews_corrcoef,
    classification_report,
    silhouette_score,
    adjusted_rand_score,
    normalized_mutual_info_score
)

from sklearn.model_selection import StratifiedKFold

warnings.filterwarnings('ignore')

"""2. Dataset description

Load dataset
"""

url ="https://raw.githubusercontent.com/shazneen342/CSE-422-Project-/refs/heads/shazneen-modify/heart_disease.csv"
df = pd.read_csv(url)

df

# CELL 1 — Load and inspect
df = df.drop(columns=['id'])
df = df.drop(columns=['dataset'])

df['num'].unique()

df.head(10)

# num is an ORDINAL categorical variable (5 severity levels: 0=No Disease, 1-4=Increasing Severity)
# We keep it as integer encoding for ML compatibility, but treat it as ordinal, not continuous.

print("Target variable 'num' — Ordinal Severity Classes:")
print("  0 = No Disease")
print("  1 = Mild")
print("  2 = Moderate")
print("  3 = Severe")
print("  4 = Very Severe (Critical)")
print()
print("Unique values:", df['num'].unique())
print("Data type: integer (ordinal encoding of categorical severity levels)")

print ('Shape of the dataset is {}. This dataset contains {} rows and {} columns.'.format(df.shape,df.shape[0],df.shape[1]))

"""**Feature Names and its Datatypes**"""

df.info()

"""Numerical Features"""

numerical_data = df.select_dtypes(include='number').drop(columns=['num'])
numerical_features = numerical_data.columns.tolist()

print(f'There are {len(numerical_features)} numerical INPUT features:\n')
print(numerical_features)

"""
Categorical Features"""

categorical_data=df.select_dtypes(include= 'object')
categorical_features=categorical_data.columns.tolist()

print(f'There are {len(categorical_features)} categorical features:', '\n')
print(categorical_features)

"""Descriptive Analysis:
Summary satistics of Numerical Features
"""

# Transposed stats for numerical features
numerical_data.describe().T

"""
Summary satistics of Categorical features"""

# Transposed stats for categorical features
categorical_data.describe().T

"""Variance of each numerical features"""

numerical_data.var()

"""Correlation Analysis

Correlation matrix of whole dataset

CORELATION
"""

# Full correlation heatmap — all features after encoding
df_corr = df.copy()
df_corr_encoded = pd.get_dummies(df_corr.drop(columns=['num']), drop_first=True)#one-hot-encoding
df_corr_encoded['num'] = df['num']  # add target back last
corr_matrix = df_corr_encoded.corr()
plt.figure(figsize=(20, 16))
#mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

sns.heatmap(
    corr_matrix,
    #mask=mask,
    cmap="coolwarm",
    vmin=-1, vmax=1,
    center=0,
    linewidths=0.3,
    annot=True,
    fmt='.2f',
    annot_kws={"size": 6}
)

plt.title("Full Feature Correlation Heatmap (All Encoded Features + Target)", fontsize=14)
plt.xticks(fontsize=7, rotation=45, ha='right')
plt.yticks(fontsize=7)
plt.tight_layout()
plt.show()

# Calculate the correlation matrix
numerical_data = df.select_dtypes(include='number').copy()
correlation_matrix = numerical_data.corr()
correlation_matrix

df = df.drop(columns=['id'], errors='ignore')
numerical_data = df.select_dtypes(include='number').copy()
corr = numerical_data.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)

plt.title('Correlation Heatmap of All Numerical Features (Input + Output)')
plt.show()

df = df.drop(columns=['id'], errors='ignore')
numerical_data = df.select_dtypes(include='number').copy()
numerical_data = numerical_data.drop(columns=['num'], errors='ignore')
numerical_data['target'] = df['num']

corr1 = numerical_data.corr(method='pearson')[['target']].sort_values(by='target', ascending=False)
corr2 = numerical_data.corr(method='spearman')[['target']].sort_values(by='target', ascending=False)
corr3 = numerical_data.corr(method='kendall')[['target']].sort_values(by='target', ascending=False)

fig, ax = plt.subplots(3, 1, figsize=(8, 12))

sns.heatmap(corr1, ax=ax[0], annot=True, cmap='coolwarm', fmt='.3f')
ax[0].set_title('Pearson Correlation (Linear Relationship)')

sns.heatmap(corr2, ax=ax[1], annot=True, cmap='viridis', fmt='.3f')
ax[1].set_title('Spearman Correlation (Monotonic Relationship)')

sns.heatmap(corr3, ax=ax[2], annot=True, cmap='magma', fmt='.3f')
ax[2].set_title("Kendall's Tau Correlation (Robust to Ties)")

plt.tight_layout()
plt.show()

"""IMBALANCE

"""

df['num'].value_counts()
#distribution of target(dataset a kotojon normal,svr patient ache)

#graphically show aager part
counts = df['num'].value_counts().sort_index()
total = len(df)
imbalance_df_plot = counts.reset_index()
imbalance_df_plot.columns = ['num', 'count']
imbalance_df_plot['percentage'] = (imbalance_df_plot['count'] / total) * 100

plt.figure(figsize=(8, 5))
ax = sns.barplot(data=imbalance_df_plot, x='num', y='count', palette='viridis')
for i, p in enumerate(ax.patches):
    percentage = imbalance_df_plot['percentage'].iloc[i]
    count = int(imbalance_df_plot['count'].iloc[i])
    ax.annotate(f'{percentage:.1f}%\n({count})',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', xytext=(0, 5),
                textcoords='offset points', fontsize=10, fontweight='bold')

plt.title("Class Distribution of Heart Disease Severity (num)", fontsize=14)
plt.xlabel("Heart Disease Level (0=No Disease, 1-4=Increasing Severity)", fontsize=11)
plt.ylabel("Count", fontsize=11)
plt.ylim(0, max(imbalance_df_plot['count']) * 1.2)
plt.show()

print(imbalance_df_plot.to_string(index=False))

"""**EDA**
Data visualization

Some other visualizations of features to get more insights
"""

# --- Skewness of numerical features ---
#bubbles are outliers
print("Skewness of numerical features:")
print(numerical_data.skew())# rgttail +ve

# --- Histograms ---
numerical_data.hist(figsize=(12, 10), bins=20)
plt.suptitle("Histograms of Numerical Features", y=1.02)
plt.tight_layout()
plt.show()

# --- Boxplots ---
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
plt.figure(figsize=(16, 20))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(x=df[col], color='skyblue')
    plt.title(f'Boxplot of {col}')
    plt.tight_layout()
plt.show()

# --- Density plots ---
numerical_data.plot(kind='density', figsize=(14, 10), subplots=True,
                    layout=(4, 2), title="Density Plots", sharex=False)
plt.tight_layout()
plt.show()

# --- Categorical bar plots ---
for col in categorical_features:
    plt.figure(figsize=(8, 4))
    df[col].value_counts().sort_index().plot(kind='bar', rot=30)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.tight_layout()
    plt.show()

# --- Numerical features vs target (boxplot per class) ---
for col in ['age', 'trestbps', 'chol', 'thalch', 'oldpeak']:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x='num', y=col, data=df, palette='Set2')
    plt.title(f'{col} vs Heart Disease Level')
    plt.tight_layout()
    plt.show()

"""

MISSING VALUE

"""

print(df.isnull().sum().sort_values(ascending=False))

missing = df.isnull().sum()
missing = missing[missing > 0]

plt.figure(figsize=(8, 4))
missing.plot(kind='bar')
plt.title("Missing Values per Feature")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# ── Handling high-missing columns ──────────────────────────────────
# 'ca'   — 611/920 values missing (66.4%) → DROP (imputing majority is unreliable)
# 'thal' — 486/920 values missing (52.8%) → DROP (same reason)
# All other features with < 10% missing → IMPUTE with median/mode
print("Dropping 'ca' due to >50% missing values")
# print(f"Features before drop: {df.shape[1]}")
df = df.drop(columns=['ca'])
print(f"Features after drop:  {df.shape[1]}")

"""IMPUTE"""

# Separate column types
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
num_cols = [c for c in num_cols if c != 'num']  # exclude target


# df['chol'] = df['chol'].replace(0, np.nan)
# df['trestbps'] = df['trestbps'].replace(0, np.nan)

# # Fill categorical with mode
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])
#average outlier diye affected
num_imputer = SimpleImputer(strategy='median')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

print("After imputation:")
print(df.isnull().sum().sort_values(ascending=False))

"""One-Hot **ENCODING**"""

# Solution: Label Encoding for binary, One-Hot for multi-category
print("Categorical features and unique values:")
for col in cat_cols:
    print(f"{col}: {df[col].unique()}")

X = df.drop(['num'], axis=1)
y = df['num'].values
X = pd.get_dummies(X, drop_first=True)

"""**Train Test Scaling**"""

# Train + Temp split
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Validation + Test split
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)#only trained data fit
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrame
X_train_final = pd.DataFrame(X_train_scaled, columns=X.columns)
X_val_final = pd.DataFrame(X_val_scaled, columns=X.columns)
X_test_final = pd.DataFrame(X_test_scaled, columns=X.columns)

print(X_train_final.describe().round(3))
print("Train:", X_train_final.shape)
print("Validation:", X_val_final.shape)
print("Test:", X_test_final.shape)

import pandas as pd
print(df.isnull().sum().sum())

train_data = X_train_final.copy()
train_data['target'] = pd.Series(y_train).values
corr_matrix = train_data.corr()
# Plot heatmap
plt.figure(figsize=(10, 10))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap (Train Set: Features + Target)')
plt.show()

"""**DECISION TREE**"""

from sklearn.metrics import ConfusionMatrixDisplay

def evaluate_multiclass(model, name, X_tr, X_te, y_tr, y_te):
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_te)

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_te)
        auc_score = roc_auc_score(y_te, y_prob, multi_class='ovr', average='macro')
    else:
        auc_score = None

    acc   = accuracy_score(y_te, y_pred)
    prec  = precision_score(y_te, y_pred, average='macro', zero_division=0)
    rec   = recall_score(y_te, y_pred, average='macro', zero_division=0)
    f1    = f1_score(y_te, y_pred, average='macro', zero_division=0)

    print(f"\n{'='*40}")
    print(f"  {name}")
    print(f"{'='*40}")
    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    if auc_score: print(f"AUC (OvR): {auc_score:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_te, y_pred, digits=4))

    # Confusion Matrix
    cm = confusion_matrix(y_te, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f"Confusion Matrix — {name}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

    return {"Model": name, "Accuracy": acc, "Precision": prec,
            "Recall": rec, "F1": f1, "AUC": auc_score if auc_score else 0}

dt_model = DecisionTreeClassifier(max_depth=10, criterion='gini',random_state=42)
dt_res = evaluate_multiclass(dt_model, "Decision Tree",
                              X_train_final, X_test_final, y_train, y_test)

"""LOGISTIC REGRESSION"""

lr_model = LogisticRegression(max_iter=1000, solver='lbfgs',
                               multi_class='multinomial', random_state=42)
lr_res = evaluate_multiclass(lr_model, "Logistic Regression",
                              X_train_final, X_test_final, y_train, y_test)

"""**NN**"""

from tensorflow.keras.utils import to_categorical

num_classes = len(np.unique(y_train))
y_train_cat = to_categorical(y_train, num_classes)
y_test_cat  = to_categorical(y_test,  num_classes)

nn_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_final.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')  # softmax for multiclass
])

nn_model.compile(optimizer='adam',
                 loss='categorical_crossentropy',
                 metrics=['accuracy'])

print("Training Neural Network...")
history = nn_model.fit(
    X_train_final, y_train_cat,
    epochs=50, batch_size=32,
    validation_split=0.2,
    verbose=1
)

# Evaluate
y_prob_nn  = nn_model.predict(X_test_final)
y_pred_nn  = np.argmax(y_prob_nn, axis=1)

nn_acc  = accuracy_score(y_test, y_pred_nn)
nn_prec = precision_score(y_test, y_pred_nn, average='macro', zero_division=0)
nn_rec  = recall_score(y_test, y_pred_nn, average='macro', zero_division=0)
nn_f1   = f1_score(y_test, y_pred_nn, average='macro', zero_division=0)
nn_auc  = roc_auc_score(y_test_cat, y_prob_nn, multi_class='ovr', average='macro')

print(f"\nNeural Network — Test Accuracy: {nn_acc:.4f}")
print(classification_report(y_test, y_pred_nn, digits=4))

# Confusion matrix
cm_nn = confusion_matrix(y_test, y_pred_nn)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_nn, annot=True, fmt='d', cmap='Greens', cbar=False)
plt.title("Confusion Matrix — Neural Network")
plt.xlabel("Predicted"); plt.ylabel("True")
plt.show()

# Learning curves
plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy', color='green', lw=2)
plt.plot(history.history['val_accuracy'], label='Val Accuracy', color='red', ls='--')
plt.title('NN: Accuracy Over Epochs'); plt.xlabel('Epochs'); plt.legend(); plt.grid(alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss', color='blue', lw=2)
plt.plot(history.history['val_loss'], label='Val Loss', color='orange', ls='--')
plt.title('NN: Loss Over Epochs'); plt.xlabel('Epochs'); plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

nn_res = {"Model": "Neural Network", "Accuracy": nn_acc, "Precision": nn_prec,
          "Recall": nn_rec, "F1": nn_f1, "AUC": nn_auc}

"""K MEANS"""

X_cluster = X.copy()
scaler2 = StandardScaler()
X_scaled_km = scaler2.fit_transform(X_cluster)

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled_km)

# Elbow Method
inertias = []
k_range = range(1, 10)
for k in k_range:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    km.fit(X_scaled_km)
    inertias.append(km.inertia_)

# Silhouette
sil_scores = []
k_range_sil = range(2, 10)
for k in k_range_sil:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    labels = km.fit_predict(X_scaled_km)
    sil_scores.append(silhouette_score(X_scaled_km, labels))

optimal_k = list(k_range_sil)[np.argmax(sil_scores)]
print(f"Optimal k: {optimal_k}")

final_km = KMeans(n_clusters=optimal_k, init='k-means++', n_init=10, random_state=42)
cluster_labels = final_km.fit_predict(X_scaled_km)

sil = silhouette_score(X_scaled_km, cluster_labels)
ari = adjusted_rand_score(y, cluster_labels)
nmi = normalized_mutual_info_score(y, cluster_labels)
print("===== K-Means Clustering Summary =====")
print(f"Optimal k        : {optimal_k}")
print(f"Silhouette Score : {sil:.4f}  (higher = better separated clusters)")
print(f"Adjusted Rand    : {ari:.4f}  (similarity to true labels)")
print(f"NMI Score        : {nmi:.4f}  (mutual info with true labels)")
# Plots
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes[0,0].plot(k_range, inertias, 'bo-'); axes[0,0].set_title("Elbow Method")
axes[0,0].set_xlabel("k"); axes[0,0].set_ylabel("Inertia"); axes[0,0].grid(True)

axes[0,1].plot(k_range_sil, sil_scores, 'ro-')
axes[0,1].axvline(optimal_k, ls='--', color='green')
axes[0,1].set_title("Silhouette Scores"); axes[0,1].grid(True)

sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=cluster_labels,
                palette='Set2', s=30, ax=axes[1,0])
axes[1,0].set_title("K-Means Clusters (PCA 2D)")
sns.countplot(x=cluster_labels, hue=y, ax=axes[1,1])
axes[1,1].set_title("Cluster vs True Class")
plt.tight_layout(); plt.show()

from sklearn.preprocessing import label_binarize
classes = sorted(np.unique(y))
y_test_bin = label_binarize(y_test, classes=classes)

all_results = pd.DataFrame([lr_res, dt_res, nn_res])
all_results = all_results.sort_values("Accuracy", ascending=False)

print("\n--- Final Model Comparison ---")
print(all_results.to_string(index=False))

metrics = ["Accuracy", "Precision", "Recall", "F1", "AUC"]
all_results.set_index("Model")[metrics].plot(
    kind="bar", figsize=(12, 6), width=0.75, colormap='viridis'
)
plt.title("Supervised Model Performance Comparison", fontsize=14)
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.ylim(0, 1.15)
plt.legend(bbox_to_anchor=(1.05, 1))
plt.tight_layout()
plt.show()

# ROC Curves (One-vs-Rest, macro)
from sklearn.preprocessing import label_binarize

classes = sorted(np.unique(y))
y_test_bin = label_binarize(y_test, classes=classes)

y_prob_lr = lr_model.predict_proba(X_test_final)
y_prob_dt = dt_model.predict_proba(X_test_final)
y_prob_nn = nn_model.predict(X_test_final)

class_names = {0: "No Disease", 1: "Mild", 2: "Moderate", 3: "Severe", 4: "Critical"}
colors_lr = 'blue'
colors_dt = 'green'
colors_nn = 'red'

fig, axes = plt.subplots(1, 5, figsize=(25, 5))

for i, cls in enumerate(classes):
    ax = axes[i]

    # Logistic Regression
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_lr[:, i])
    ax.plot(fpr, tpr, color='blue', lw=2,
            label=f'LR (AUC={auc(fpr,tpr):.2f})')

    # Decision Tree
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_dt[:, i])
    ax.plot(fpr, tpr, color='green', lw=2,
            label=f'DT (AUC={auc(fpr,tpr):.2f})')

    # Neural Network
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_nn[:, i])
    ax.plot(fpr, tpr, color='red', lw=2, ls='--',
            label=f'NN (AUC={auc(fpr,tpr):.2f})')

    ax.plot([0,1],[0,1],'k--', alpha=0.4)
    ax.set_title(f'Class {cls}: {class_names[cls]}', fontsize=11)
    ax.set_xlabel('False Positive Rate')
    ax.set_ylabel('True Positive Rate')
    ax.legend(loc='lower right', fontsize=8)
    ax.grid(alpha=0.3)

plt.suptitle('ROC Curves per Class (One-vs-Rest) — All Models', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

"""**TEST CASE**"""

import numpy as np


num_samples = min(92, len(X_test_final))
random_indices = np.random.choice(len(X_test_final), num_samples, replace=False)

# multiclass labels
disease_map = {
    0: "No Disease",
    1: "Mild",
    2: "Moderate",
    3: "Severe",
    4: "Critical"
}

X_test_np = X_test_final.values if hasattr(X_test_final, 'values') else X_test_final

print(f"{'ID':<7} | {'Actual':<12} | {'DT':<12} | {'LR':<12} | {'NN':<12}")
print('-' * 70)

summary_results = []

for idx in random_indices:
    actual_class = y_test[idx]

    # predictions
    dt_pred = dt_model.predict(X_test_np[[idx]])[0]
    lr_pred = lr_model.predict(X_test_np[[idx]])[0]

    nn_probs = nn_model.predict(X_test_np[[idx]], verbose=0)[0]
    nn_pred = np.argmax(nn_probs)

    # convert to labels
    actual = disease_map[actual_class]
    dt_p = disease_map[dt_pred]
    lr_p = disease_map[lr_pred]
    nn_p = disease_map[nn_pred]

    print(f"{idx:<7} | {actual:<12} | {dt_p:<12} | {lr_p:<12} | {nn_p:<12}")

    summary_results.append({
        'Actual': actual_class,
        'DT': dt_pred,
        'LR': lr_pred,
        'NN': nn_pred
    })

print('-' * 70)

for model_key in ['DT', 'LR', 'NN']:
    correct = sum(1 for r in summary_results if r['Actual'] == r[model_key])
    print(f'{model_key} Correct: {correct}/{num_samples}')

import numpy as np
import pandas as pd

# Ensure we use exactly 92 samples or the maximum available
num_samples = min(92, len(X_test_final))
random_indices = np.random.choice(len(X_test_final), num_samples, replace=False)

# Multiclass labels mapping
disease_map = {
    0: "No Disease",
    1: "Mild",
    2: "Moderate",
    3: "Severe",
    4: "Critical"
}

# Convert X_test to numpy for easier indexing if it isn't already
X_test_np = X_test_final.values if hasattr(X_test_final, 'values') else X_test_final

# Header
print(f"{'ID':<7} | {'Actual':<12} | {'DT':<12} | {'LR':<12} | {'NN':<12}")
print('-' * 70)

summary_results = []

for idx in random_indices:
    # Handle y_test indexing (pandas vs numpy)
    if isinstance(y_test, (pd.Series, pd.DataFrame)):
        actual_class = y_test.iloc[idx]
    else:
        actual_class = y_test[idx]

    # Model Predictions
    dt_pred = dt_model.predict(X_test_np[[idx]])[0]
    lr_pred = lr_model.predict(X_test_np[[idx]])[0]

    # Neural Network Prediction (argmax to get the class with highest probability)
    nn_probs = nn_model.predict(X_test_np[[idx]], verbose=0)[0]
    nn_pred = np.argmax(nn_probs)

    # Convert numeric classes to readable labels
    actual = disease_map[actual_class]
    dt_p = disease_map[dt_pred]
    lr_p = disease_map[lr_pred]
    nn_p = disease_map[nn_pred]

    # Print Row
    print(f"{idx:<7} | {actual:<12} | {dt_p:<12} | {lr_p:<12} | {nn_p:<12}")

    # Store for final tally
    summary_results.append({
        'Actual': actual_class,
        'DT': dt_pred,
        'LR': lr_pred,
        'NN': nn_pred
    })

print('-' * 70)

# Final Accuracy Tally
for model_key in ['DT', 'LR', 'NN']:
    correct = sum(1 for r in summary_results if r['Actual'] == r[model_key])
    accuracy = (correct / num_samples) * 100
    print(f'{model_key} Total Correct: {correct}/{num_samples} ({accuracy:.2f}%)')